services:
  web:
    environment:
      - HOST="repoti.ir"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    expose:
      - "3000"

  nginx:
    build: ./infra/nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"