services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    expose:
      - "3000"
    networks:
      - appnet

  nginx:
    build: ./infra/nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge